export interface OrderOperating {
  id: number;
  vehicle: string;
  driverName: string;
  nameDistributor: string;
  ItemId: number;
  NameProduct: string;
  CatId: string;
  SumNumber: number
  TimeIn33: Date;
  CardNo: string;
  OrderId: number;
  DeliveryCode: string;
  DeliveryCodeParent: string;
  OrderDate: Date;
  TypeProduct: string;
  TimeIn21: Date;
  TimeIn22: Date;
  Confirm1: number;
  TimeConfirm1: Date;
  Confirm2: number;
  TimeConfirm2: Date;
  Confirm3: number;
  TimeConfirm3: Date;
  Confirm4: number;
  TimeConfirm4: Date;
  Confirm5: number;
  TimeConfirm5: Date;
  Confirm6: number;
  TimeConfirm6: Date;
  Confirm7: number;
  TimeConfirm7: Date;
  Confirm8: number;
  TimeConfirm8: Date;
  Confirm9: number;
  TimeConfirm9: Date;
  Confirm9Note: string;
  Confirm9Image: string;
  Step: number;
  IndexOrder: number;
  IndexOrder1: number;
  IndexOrder2: number;
  Trough: number;
  Trough1: number;
  NumberVoice: number;
  State: string;
  Prioritize: number;
  DayCreate: Date;
  IDDistributorSyn: number;
  AreaId: number;
  AreaName: string;
  CodeStore: string;
  NameStore: string;
  DriverUserName: string;
  DriverAccept: Date;
  IndexOrderTemp: number;
  WeightIn: number;
  WeightInTime: Date;
  WeightOut: number;
  WeightOutTime: Date;
  NoteFinish: string;
  Longitude: string;
  Latitude: string;
  CountReindex: number;
  IsVoiced: boolean;
  LocationCode: string;
  LockInDbet: boolean;
  LogJobAttach: string;
  IsSyncedByNewWS: boolean;
  TroughLineCode: string;
  IsScaleAuto: boolean;
  TimeConfirmHistory: Date;
  LogHistory: string;
  MoocCode: string;
  LogProcessOrder: string;
  DriverPrintNumber: number;
  DriverPrintTime: Date;
  WarningNotCall: boolean;
  XiRoiAttatchmentFile: string;
  PackageNumber: string;
  Shifts: number;
  AutoScaleOut: boolean;
  CreateDay: Date;
  CreateBy: string;
  UpdateDay: Date;
  UpdateBy: string;
}
export interface lstOrderOperating {
  currentPage: number,
  pageSize: number,
  totalRecord: number,
  totalPage: number
  data: OrderOperating[]
}
