export interface OrderOperating {
  id: number
  vehicle: string
  driverName: string
  nameDistributor: string
  itemId: number
  nameProduct: string
  catId: string
  sumNumber: number
  timeIn33: Date
  cardNo: string
  orderId: number
  deliveryCode: string
  deliveryCodeParent: string
  orderDate: Date
  typeProduct: string
  timeIn21: Date
  timeIn22: Date
  confirm1: number
  timeConfirm1: Date
  confirm2: number
  timeConfirm2: Date
  confirm3: number
  timeConfirm3: Date
  confirm4: number
  timeConfirm4: Date
  confirm5: number
  timeConfirm5: Date
  confirm6: number
  timeConfirm6: Date
  confirm7: number
  timeConfirm7: Date
  confirm8: number
  timeConfirm8: Date
  confirm9: number
  timeConfirm9: Date
  confirm9Note: string
  confirm9Image: string
  step: number
  indexOrder: number
  indexOrder1: number
  indexOrder2: number
  trough: number
  trough1: number
  numberVoice: number
  state: string
  prioritize: number
  dayCreate: Date
  iDDistributorSyn: number
  areaId: number
  areaName: string
  codeStore: string
  nameStore: string
  driverUserName: string
  driverAccept: Date
  indexOrderTemp: number
  weightIn: number
  weightInTime: Date
  weightOut: number
  weightOutTime: Date
  noteFinish: string
  longitude: string
  latitude: string
  countReindex: number
  isVoiced: boolean
  locationCode: string
  lockInDbet: boolean
  logJobAttach: string
  isSyncedByNewWS: boolean
  troughLineCode: string
  isScaleAuto: boolean
  timeConfirmHistory: Date
  logHistory: string
  moocCode: string
  logProcessOrder: string
  driverPrintNumber: number
  driverPrintTime: Date
  warningNotCall: boolean
  xiRoiAttatchmentFile: string
  packageNumber: string
  shifts: number
  autoScaleOut: boolean
  createDay: Date
  createBy: string
  updateDay: Date
  updateBy: string
}
export interface lstOrderOperating {
  currentPage: number,
  pageSize: number,
  totalRecord: number,
  totalPage: number
  data: OrderOperating[]
}
